### ISSUE TITLE
any plan for php7 and apcu ?

### ISSUE THREAD

**Issue by JOduMonT** [tipichris/YAPCache#2]
Hi;

I just discover your plugins
and on my lemp (debian9) APC become APCu with PHP7
```
root@server:~# php -m|grep apc
apcu
```

but your plugins complain about not founding apc

so any plan of supporting apcu ?

Regards!

Jonathan

**Comment by tipichris** [comment]
Have you looked at https://github.com/krakjoe/apcu-bc?

I don't currently have plans to upgrade my installation to PHP7 and I'm unlikely to do any work on this plugin until I need to.

**Comment by JOduMonT** [comment]
thanks for your quick follow and your potential resolution

so I tried with apcu-bc (by simply apt install php-apcu-bc)

![screenshot_2018-10-11_09-00-23](https://user-images.githubusercontent.com/5204724/46786149-4b4b0000-cd34-11e8-9b38-5c788a95b0bd.png)

but still have a blank page when I'm activating your plugin.

Anyway for now it was just a test and I don't really need extra caching

:)
